In [1]:
import numpy as np

In [2]:
list = [20,30,40,40]
print(list)

[20, 30, 40, 40]


In [3]:
arr = np.array([20, 30, 40, 50])
print(arr)

[20 30 40 50]


In [4]:
# datatype

arr = np.array([1,2,3.0,4.6,5.8,6,7,8])
print(arr.dtype)

float64


In [5]:
# Conversion of datatype

arr = np.array([1,2,3.0,4.6,5.8,6,7,8])
print(arr.dtype)
print(arr.astype(int))

float64
[1 2 3 4 5 6 7 8]


In [6]:
# Cheaking shape of an array ((a,b) where a shows rows and b represents elements in column)

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]]) 
print(arr.shape) 

print(arr.size)

(2, 4)
8


In [7]:
# Reshaping array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) 
newarr = arr.reshape(4, 3) 
print(newarr) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
# Iterating elements

arr = np.array([1, 2, 3]) 
for x in arr: 
     print(x) 

1
2
3


In [9]:
# Joining array

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.concatenate((arr1,arr2))
print(newarr)

[1 2 3 4 5 6]


In [10]:
# Splitting array

arr = np.array([1, 2, 3, 4, 5, 6]) 
newarr = np.array_split(arr, 3) 
print(newarr) 

[array([1, 2]), array([3, 4]), array([5, 6])]


In [11]:
# Searching array(It returns with index)

arr = np.array([1,2,3,4,5,6,7,8])
x=np.where(arr==8)
print(x)

(array([7], dtype=int64),)


In [ ]:
# Sorting array

arr1 = np.array([3,6,2,7,9,2,0])         
print(np.sort(arr1))

arr2 = np.array([3,7,1,0,9,7])         
print(np.sort(arr2)[::-1])

In [12]:
arr1 = np.array([3,6,2,7,9,2,0])         
print(np.sort(arr1))

[0 2 2 3 6 7 9]


In [13]:
arr2 = np.array([3,7,1,0,9,7])          
print(np.sort(arr2)[::-1])

[9 7 7 3 1 0]


In [14]:
arr = np.array([41, 42, 43, 44]) 
x = [True, False, True, False] 
newarr = arr[x] 
print(newarr) 

[41 43]


In [15]:
arr = np.array([41, 42, 43, 44])                                 
                                           
filter_arr = [] 
 
for element in arr: 
 
     if element > 42: 
          filter_arr.append(True) 
     else: 
          filter_arr.append(False)

newarr = arr[filter_arr] 

print(filter_arr)

print(newarr) 

[False, False, True, True]
[43 44]


In [16]:
arr = np.array([20,30,40])
print(np.append(arr,[50,60]))

print(np.insert(arr,2,[90,80]))         

print(np.delete(arr,[1]))

[20 30 40 50 60]
[20 30 90 80 40]
[20 40]


In [17]:
# Aggregating functions

a = np.array([20,30,40,50])

# sum of all elements
print(np.sum(a))

# Minimum
print(np.min(a))

# maximum
print(np.max(a))

# Cumulative sum
print(np.cumsum(a))

140
20
50
[ 20  50  90 140]


In [18]:
# Statistical Functions

import statistics as stats

food_price = [20,30,40,50,60,70,20,30,20,30]
a = np.array(food_price)

# Mean 
print(np.mean(a))

# Median 
print(np.median(a))

# Mode
print(stats.mode(a))

37.0
30.0
20
